import { IProjects } from "./typeHelper";

export const projects: IProjects[] = [
  {
    title: "Covid19 SafeZone",
    description: "Application shows the location of people who have been vaccinated.",
    imageUrl: "howto.png",
    tag: "Mobile",
    technologies: ["React-Native", "JS", "Firebase"],
    githubLink: "https://github.com/aomsk/Covid-Safe-ZoneApp",
    previewLink: "",
  },
  {
    title: "Ha Ha How To",
    description: "A web application collects ways to do things.",
    imageUrl: "howto.png",
    tag: "FullStack",
    technologies: ["React", "JS", "AWS", "Express"],
    githubLink: "https://github.com/aomsk/Ha-Ha-How-To",
    previewLink: "",
  },
  {
    title: "Kaew - Ta",
    description: "Objects Detection application for visually impaired.",
    imageUrl: "howto.png",
    tag: "Mobile",
    technologies: ["React-Native", "JS", "ML"],
    githubLink: "https://github.com/aomsk/Object-Detection-App",
    previewLink: "",
  },
  {
    title: "Tip Calculator",
    description: "Calculate the correct tip and total cost of the bill per person",
    imageUrl: "tip-calculator-app-creenshot.png",
    tag: "Frontend",
    technologies: ["React", "TS", "Tailwind"],
    githubLink: "https://github.com/aomsk/tip-calculator-app",
    previewLink: "https://tip-calculator-app-aomsk.vercel.app/",
  },
  {
    title: "Todo List",
    description: "Todo Lists help you manage tasks. more easily",
    imageUrl: "todoList.png",
    tag: "FullStack",
    technologies: ["React", "TS", "Tailwind", "Express"],
    githubLink: "https://github.com/aomsk/todolist-fullStack",
    previewLink: "",
  },
  {
    title: "Shopping Store",
    description: "Shopping-Store",
    imageUrl: "shopping-store.png",
    tag: "Frontend",
    technologies: ["React", "TS", "Tailwind", "API"],
    githubLink: "https://github.com/aomsk/shopping-store",
    previewLink: "https://shopping-store-aomsk.netlify.app/",
  },
  {
    title: "Advice Generator",
    description: "Advice Generator",
    imageUrl: "advice-generator-app.png",
    tag: "Frontend",
    technologies: ["React", "TS", "Tailwind", "API"],
    githubLink: "https://github.com/aomsk/advice-generator-app",
    previewLink: "https://advice-generator-app-aomsk.vercel.app/",
  },
  {
    title: "Pokemon",
    description: "Pokemon",
    imageUrl: "pokemon.png",
    tag: "Frontend",
    technologies: ["React", "JS", "bootstrap", "API"],
    githubLink: "https://github.com/aomsk/pokemon-react",
    previewLink: "https://pokemon-react-drab.vercel.app/",
  },
  {
    title: "BMI Calculator",
    description: "BMI Calculator",
    imageUrl: "bmi.png",
    tag: "Frontend",
    technologies: ["React", "TS", "Tailwind"],
    githubLink: "https://github.com/aomsk/bmi-calculator",
    previewLink: "https://bmi-calculator-aomsk.vercel.app/",
  },
  {
    title: "Sunnyside",
    description: "Sunnyside",
    imageUrl: "sunnyside.png",
    tag: "Frontend",
    technologies: ["HTML", "CSS"],
    githubLink: "https://github.com/aomsk/sunnyside-agency-landing-page",
    previewLink: "https://aomsk.github.io/sunnyside-agency-landing-page/",
  },
  {
    title: "Interactive Rating",
    description: "Interactive Rating",
    imageUrl: "interactive-rating.png",
    tag: "Frontend",
    technologies: ["React", "Tailwind"],
    githubLink: "https://github.com/aomsk/interactive-rating-component",
    previewLink: "https://interactive-rating-component-aomsk.vercel.app/",
  },
  {
    title: "Stats preview card",
    description: "Stats preview card",
    imageUrl: "stats- preview.png",
    tag: "Frontend",
    technologies: ["React", "Tailwind"],
    githubLink: "https://github.com/aomsk/stats-preview-card-component",
    previewLink: "https://stats-preview-card-component-aomsk.vercel.app/",
  },
];
